server:
  port: 8081
spring:
  application:
    name: zuulserver
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    users:
      path: /oauth/**
      url: http://localhost:8080/
jwt:
  secret: MuhammedShehab
